export const artistsContent = [
  {
    name: 'Huma',
    bio: [
      'Huma is the personal project of Andrés Satué. Born in Galicia but based in Barcelona, he has an extensive career in musical experimentation, from his first math-kraut-rock and prog bands, to experimental electronics with his previous project Esquelas and now with Huma. He has released several albums under labels including Bestiarie, ENSMBLE and Matapadre. He participated in the Red Bull Music Academy Bass Camp in Madrid, played at some of the most relevant Spanish experimental electronics festivals and is co-founder of Hedonic Reversal label and Bicefal Festival. He also runs a monthly radio show with his label partner Miguel Sueiro at Dublab Barcelona.',
    ],
    picture: 'huma.jpg',
    links: {
      facebook: 'https://www.facebook.com/Huma4444',
      soundcloud: 'https://soundcloud.com/huma4444',
      instagram: 'https://www.instagram.com/huma_4444',
    },
    releases: [
      {
        id: 1,
        albumId: '1635759303',
        title: 'Las tres fases del movimiento',
        catNumber: 'HEDREV-00001',
        releaseDate: '17 November 2016',
        format: 'Vinyl / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/las-tres-fases-del-movimiento',
        credits: [
          'Written and produced by Andrés Satué',
          'Mastered by Pedro Pina',
          'Art direction and design by Miguel Sueiro',
          '© 2016 www.hedonicreversal.com',                     
        ],
        description: [
          'Huma is the personal project of Andrés Satué, half of the duo Esquelas, project in which they released “Inciso” (Ensmble) and more recently “Un pozo lleno de anzuelos” (Bestiarie). He was participant in the RedBull Muisc Academy BassCamp in Madrid 2015. He is also cofounder of Versal and Bicefal.',
          'This is his first EP as Huma. “Las tres fases del movimiento" is based on two ideas, on one hand the three phases of movement of Meyerhold biomechanics, and on the other hand the three phases of movement in bodybuilding. Joining these two ideas he generates a very physical, visceral and emotional journey.',
          '«A visceral and emotion-laden situation that sometimes seems to set in front of the abyss, but the most important thing is that it generates a movement.» —David Gozálvez, Neonized',
          '"... Huma manages to make his music a purely corporeal act: his cuts are like dancers who move in complex and different ways in space. Sometimes they move as if they want to touch the sky ... » — Fantastic Plastic',
          '«The intersection between extreme, saturation and depth is what describes this new project of Andrés Satué ...» — Frankie Pizá, This Is Underground',
        ],
        images: [
          'huma-tresfases-01.jpg',
          'huma-tresfases-02.jpg',
          'huma-tresfases-03.jpg',
          'huma-tresfases-04.jpg',
          'huma-tresfases-05.jpg',          
        ],
        coverImage: 'huma-tresfases-cover.jpg',
        listPosition: 1,
      },
      {
        id: 2,
        albumId: '2733975405',
        title: 'Yocto / Yotta',
        catNumber: 'HEDREV-00002',
        releaseDate: '10 March 2018',
        format: 'Vinyl / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/yocto-yotta',
        credits: [
          'Written and produced by Andrés Satué',
          'Mastered by Pedro Pina',
          'Art direction and design by Miguel Sueiro',
          '© 2018 www.hedonicreversal.com',                      
        ],
        description: [
          'Two new tracks after Humas 2016 first EP «Las tres fases del movimiento',
          'Yocto (symbol y) is a prefix of the International System that indicates a factor of 10-24.',
          'Yotta (symbol Y) is a prefix of the International System that indicates a factor of 1024 (a quadrillion).',
        ],
        images: [
          'huma-yocto-00.jpg',
        ],
        coverImage: 'huma-yocto-cover.jpg',
        listPosition: 3,
      },    
      {
        id: 3,
        albumId: '3277444269',
        title: 'Eva',
        catNumber: 'HEDREV-00006',
        releaseDate: '11 November 2019',
        format: 'Cassette / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/eva-2',
        credits: [
          'Written and produced by Andrés Satué',
          'Mastered by Matt Colton at Alchemy Mastering',
          'Art direction and design by Miguel Sueiro',
          'Cover illustration by Martina Ampuero',
          '© 2019 www.hedonicreversal.com',                     
        ],
        description: [
          'Eva is a journey from the birth of humanity (Adán) to the rebirth of the new human (Eva). With a positive but disturbing point of view it delves into the idea of technological singularity and the consequences of the exponential growth of human development. In order to do so, it explores in an extreme and profound way the relationships between concepts such as micro/macro, organic/inorganic, natural/artificial, man/machine.',
        ],
        images: [
          'huma-eva-01.jpg',
          'huma-eva-02.jpg',
          'huma-eva-03.jpg',
          'huma-eva-04.jpg',          
        ],
        coverImage: 'huma-eva-cover.jpg',
        listPosition: 7,
      },  
      {
        id: 4,
        albumId: '695194201',
        title: 'Eva Remixes',
        catNumber: 'HEDREV-00006b',
        releaseDate: '26 November 2019',
        format: 'Cassette / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/eva-remixes',
        credits: [
          'Written and produced by Andrés Satué',
          'Mastered by Matt Colton at Alchemy Mastering',
          'Art direction and design by Miguel Sueiro',
          'Cover illustration by Martina Ampuero',          
          '© 2019 www.hedonicreversal.com',             
        ],
        description: [
          'Eva is a journey from the birth of humanity (Adán) to the rebirth of the new human (Eva). With a positive but disturbing point of view it delves into the idea of technological singularity and the consequences of the exponential growth of human development. In order to do so, it explores in an extreme and profound way the relationships between concepts such as micro/macro, organic/inorganic, natural/artificial, man/machine.',
        ],
        images: [
          'huma-evaremixes-00.jpg',
        ],
        coverImage: 'huma-evaremixes-cover.jpg',
        listPosition: 5,
      },     
      {
        id: 5,
        albumId: '1673263714',
        title: 'Emergence',
        catNumber: 'HEDREV-00009',
        releaseDate: '25 February 2021',
        format: 'Cassette / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/emergence',
        credits: [
          'Written and produced by Andrés Satué',
          'Mastered by Pedro Pina',
          'Art direction and design by Miguel Sueiro',
          'Cover illustration by Mitrilo',          
          'Inner sleeve graphics created with the Wolfram Language (www.wolfram.com)',   
          '© 2021 www.hedonicreversal.com',             
        ],
        description: [
          'Emergence experiments with irregular and unpredictable structures that arise from sequences and textures colliding and merging into rhythmic and melodic sonic explorations that seem non-human-like but at the same time intuitive and almost familiar. Inspired by the Emergence Theory, which states that a large number of relatively simple elements can self-organize into behaviors that appear to be unexpectedly complex, it creates a process by which musical order seems to emerge out from chaos.',
        ],
        images: [
          'huma-emergence-00.jpg',
        ],
        coverImage: 'huma-emergence-cover.jpg',
        listPosition: 6,
      },           
    ],
  },
  // --------------------------------------------------------
  {
    name: 'Blume Attempt',
    bio: [
      'Blume Attempt is the artistic name of the Spanish artist based in Leipzig (Germany) Javier Vivancos.',
      'In his second EP «Just like you», Blume Attempt creates a sound of its own where modern electronic experimental music interweaves with strong influences of industrial music from the late 80s.',
      'After a first digital release on Banned In Vegas record label («Perpetual», 2016), Javier Vivancos does a retrospective exercise and projects more aggressive and repetitive sounds and textures in his compositions, passed through his personal filter, leading him to create four new cuts that suppose his first recordings for Hedonic Reversal.',
    ],
    picture: 'blume.jpg',
    links: {
      facebook: 'https://www.facebook.com/blumeattempt',
      soundcloud: 'https://soundcloud.com/blumeattempt',
      instagram: 'https://soundcloud.com/blumeattempt',
    },
    releases: [
      {
        id: 6,
        albumId: '2436117798',
        title: 'Just Like You',
        catNumber: 'HEDREV-00003',
        releaseDate: '23 May 2018',
        format: 'Vinyl / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/just-like-you',
        credits: [
          'Written and produced by Blume Attempt',
          'Sax in «Seed» by Hans Betancourth',
          'Mastered by Pedro Viñuela',
          'Art direction and design by Miguel Sueiro',
          'Photography by Sophie Valentin',
        ],
        description: [
          'In his second EP «Just like you», Blume Attempt creates a sound of its own where modern electronic experimental music interweaves with strong influences of the late 80’s industrial music.',
          'After a first digital release on Banned in Vegas record label ("Perpetual", 2016), Javier Vivancos does a retrospective exercise and projects more aggressive and repetitive sounds and textures in his compositions passed through his personal filter, leading him to create four new cuts that involve his first recordings for Hedonic Reversal.',
        ],
        images: [
          'blumeattempt-justlikeyou-01.jpg',
          'blumeattempt-justlikeyou-02.jpg',
          'blumeattempt-justlikeyou-03.jpg',
          'blumeattempt-justlikeyou-04.jpg',
          'blumeattempt-justlikeyou-05.jpg',
          'blumeattempt-justlikeyou-06.jpg',          
        ],
        coverImage: 'blumeattempt-justlikeyou-cover.jpg',
        listPosition: 2,
      },
    ],
  },
  // --------------------------------------------------------
  {
    name: 'Refectori',
    bio: [
      'Refectori (Xavier Longàs) has performed in different halls and festivals in Barcelona as Bicefal festival, also in the third and fourth WAV Conference that were celebrated in El Pumarejo and in Hangar respectively, likewise took sounds next to techno in Kreuzberg Club organized by Diffuse Reality and with the HEX collective has participated in his second episode in The Loft of Razzmatazz.',
    ],
    picture: 'refectori.jpg',
    releases: [
      {
        id: 8,
        albumId: '466129291',
        title: 'Espleni',
        catNumber: 'HEDREV-00004',
        releaseDate: '05 April 2019',
        format: 'Vinyl / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/espleni',
        credits: [
          'Produced by Xavier Longàs',
          'Mastered by Pedro Pina',
          'Art direction & Design Miguel Sueiro',
          'Photograhpy by Eva Paià',
          '© 2019 www.hedonicreversal.com',                     
        ],
        description: [
          'From the physical transformation of organic elements that melt generating new textures, Espleni is created. Fragmented into nine pieces, it starts with an inmersive melody starting a route without return where you can explore frozen territories of heavy structures. This reflects the union between body and raw material, an interest that was already glimpsed in its first release with Bestiarie (2015). The distortion of organic sounds arrives to wide landscapes of noise, sometimes moderated and in others uncontrolled. Noises that are juxtaposed in a constant dialogue until its definitive bifurcation.',
          'This project starts from the recording of everyday sounds that surround the author, using a Zoom H5 recorder, with which he later experiments, manipulating and gathering them until creating a musically harmonic composition.',
          'He has performed in different halls and festivals in Barcelona as Bicefal festival, also in the third and fourth WAV Conference that were celebrated in El Pumarejo and in Hangar respectively, likewise took sounds next to techno in Kreuzberg Club organized by Diffuse Reality and with the HEX collective has participated in his second episode in The Loft of Razzmatazz.',
        ],
        images: [
          'refectori-espleni-01.jpg',
          'refectori-espleni-02.jpg',
          'refectori-espleni-03.jpg',
          'refectori-espleni-04.jpg',
          'refectori-espleni-05.jpg',          
        ],
        coverImage: 'refectori-espleni-cover.jpg',
        listPosition: 4,
      },
    ],
  },
  // --------------------------------------------------------
  {
    name: 'Huma',
    bio: [
      'Refectori (Xavier Longàs) has performed in different halls and festivals in Barcelona as Bicefal festival, also in the third and fourth WAV Conference that were celebrated in El Pumarejo and in Hangar respectively, likewise took sounds next to techno in Kreuzberg Club organized by Diffuse Reality and with the HEX collective has participated in his second episode in The Loft of Razzmatazz.',
    ],
    picture: 'orphan-swords.jpg',
    releases: [
      {
        id: 9,
        albumId: '466129291',
        title: 'Just Like You',
        catNumber: 'HEDREV-00004',
        releaseDate: '21 June 2019',
        format: 'Vinyl / Digital',
        buyUrl: 'https://hedonicreversal.bandcamp.com/album/espleni',
        credits: [
          'Produced by Xavier Longàs',
          'Mastered by Pedro Pina',
          'Art direction & Design Miguel Sueiro',
          'Photograhpy by Eva Paià',
        ],
        description: [
          'From the physical transformation of organic elements that melt generating new textures, Espleni is created. Fragmented into nine pieces, it starts with an inmersive melody starting a route without return where you can explore frozen territories of heavy structures. This reflects the union between body and raw material, an interest that was already glimpsed in its first release with Bestiarie (2015). The distortion of organic sounds arrives to wide landscapes of noise, sometimes moderated and in others uncontrolled. Noises that are juxtaposed in a constant dialogue until its definitive bifurcation.',
          'This project starts from the recording of everyday sounds that surround the author, using a Zoom H5 recorder, with which he later experiments, manipulating and gathering them until creating a musically harmonic composition.',
          'He has performed in different halls and festivals in Barcelona as Bicefal festival, also in the third and fourth WAV Conference that were celebrated in El Pumarejo and in Hangar respectively, likewise took sounds next to techno in Kreuzberg Club organized by Diffuse Reality and with the HEX collective has participated in his second episode in The Loft of Razzmatazz.',
        ],
        images: [
          'back-vinyl.gif',
          'back.gif',
        ],
        coverImage: 'cover.jpg',
        listPosition: 8,
      },
    ],
  },
  // --------------------------------------------------------
]
